server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/egedb
    username: postgres
    password: 3896
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: your-256-bit-secret-key-here-1234567890abcdef